### ISSUE TITLE
No default OFF command for HarmonyHub Node

### ISSUE THREAD

**Issue by shbatm** [jimboca/harmonyhub-polyglot#11]
I want to be able to add one of my hubs to my "All Off" scene in my ISY to have it switch the activity to Power Off...

Would it be possible to have a default OFF command (just starting with ns development but would that be a `<sends><cmd id="DOF" /></sends>` command?) on the HarmonyHub node that sets the hub's current activity to 'Power Off'?

I know I could just grab any of the activity nodes and turn it off, but I thinking this may be cleaner?

**Comment by jimboca** [comment]
Yes, that is a good idea.  I'm not sure what lets the ISY know that it can be in a scene, I'd assume it needs to be in the accepts section.  You could manually add it to the profile if you want to try? and if that allows it to be added to the scene, then I can implement the command, but I won't have time for a couple days.

**Comment by shbatm** [comment]
@jimboca - I appreciate the quick response.  I'm using this as a way to learn more about node server development so I took a stab at what I think would fix the problem. See the commit on my fork above when you get time; if it works, I'll send a Pull Request.

Summary: the Hub node can be added to scenes and the scene controllers will send a "default" command when they are triggered.  This can be changed in the scene controller's configuration for when the scene is turned "ON"; however, at the moment it doesn't look like you can configure what it sends on an "OFF" or "FAST OFF" for the scene.  This attempt at an update added a command to the hub node for `DOF` and `DFOF` commands to just call `start_activitiy(index=-1)` and set the activity to `Power Off`.

**Comment by jimboca** [comment]
@shbatm That looks great!  Really appreciate the help.  My only comment would be to use spaces instead of tabs, I hate tabs :) Then if it works for you, increment the version minor in harmony_hub_polyglot_version.py and submit the pull request.

**Comment by shbatm** [comment]
PR sent, I'm with you on the spaces, went back and cleaned up what I touched to fix my OCD. 

This is tested on my setup and correctly turns the Hub to "Power Off" when the HarmonyHub node (not server) is added to a scene and the scene is given either a `DOF` or `DFOF` command.
